import {toMemoryInput} from './validateMemoryInput';
import type {MemoryInput} from '../../types/memory';

export interface ConversationTurn {
  role: 'user' | 'assistant';
  text: string;
  /**
   * Set when this turn's content originated from a tool result
   * (web_search, read_url, etc.) rather than being written by the user or
   * generated by the model on its own. Any candidate extracted from a
   * window containing such a turn cannot be certified as the user's own
   * words, whatever the extraction model itself claims about it.
   */
  source?: 'external_content';
}

/**
 * A completion function, injected rather than hardcoded to a specific
 * model-loading mechanism — same discipline as EmbeddingEngine's
 * decoupling from ModelStore. The caller decides which loaded model (the
 * small draft model, per the design this pipeline was built against) this
 * actually runs against; this module only needs "text in, text out."
 */
export type CompletionFn = (prompt: string) => Promise<string>;

const EXTRACTION_PROMPT_HEADER = `You are a memory extraction assistant. Read the conversation excerpt below and decide what, if anything, is worth remembering long-term about the user: durable facts, preferences, events, or open threads to follow up on. Ignore one-off task chatter (e.g. debugging details, a single calculation) unless it reveals a lasting preference. Do not invent details that were not stated or clearly implied.

Respond with a JSON array only, no other text and no markdown code fence. Each item must have this shape:
{"content": string, "kind": "fact" | "preference" | "episodic" | "procedural" | "relationship" | "open_thread", "tags": string[], "provenance": "user_stated" | "model_inferred", "confidence": number between 0 and 1}
Use "user_stated" only when the user said this directly in their own words. Return [] if nothing in this excerpt is worth keeping.

Conversation:
`;

function buildPrompt(turns: ConversationTurn[]): string {
  const transcript = turns
    .map(
      turn =>
        `${turn.role}${
          turn.source === 'external_content'
            ? ' (quoting external content)'
            : ''
        }: ${turn.text}`,
    )
    .join('\n');
  return EXTRACTION_PROMPT_HEADER + transcript;
}

/**
 * Pulls a JSON array out of a completion that may have wrapped it in
 * prose or a markdown code fence — a model asked for "JSON only" cannot be
 * trusted to actually produce only JSON. Returns [] on anything that
 * doesn't parse to an array, rather than throwing.
 */
function extractJsonArray(raw: string): unknown[] {
  const match = raw.match(/\[[\s\S]*\]/);
  if (!match) {
    return [];
  }
  try {
    const parsed = JSON.parse(match[0]);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Reads a window of conversation turns and proposes candidate long-term
 * memories. Pure with respect to storage: it never writes to
 * MemoryRepository itself — persisting (with or without an embedding) and
 * any future dedup/consolidation pass is the caller's job, so this stays
 * testable in isolation and easy to reason about independent of storage
 * concerns.
 */
export async function extractMemoryCandidates(
  turns: ConversationTurn[],
  complete: CompletionFn,
): Promise<MemoryInput[]> {
  if (turns.length === 0) {
    return [];
  }

  const hasExternalContent = turns.some(
    turn => turn.source === 'external_content',
  );

  let raw: string;
  try {
    raw = await complete(buildPrompt(turns));
  } catch (error) {
    console.error('MemoryExtractionPipeline: completion failed:', error);
    return [];
  }

  const rawCandidates = extractJsonArray(raw);
  const candidates: MemoryInput[] = [];
  for (const rawCandidate of rawCandidates) {
    if (typeof rawCandidate !== 'object' || rawCandidate === null) {
      continue;
    }
    const input = toMemoryInput(rawCandidate as Record<string, any>, {
      disallowUserStated: hasExternalContent,
    });
    if (input) {
      candidates.push(input);
    }
  }
  return candidates;
}
